# spring.application.name=be_e-commerce

app:
  frontend-url: http://localhost:5173

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/be_e-commerce
    username: root
    password: Vuong123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: tranvuong3101@gmail.com
    password: ihtbkremfkzxyjnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
jwt:
  secret-key: "0wyVcEIcIZR6ntVz/xbrFhH7l6izZZI8ob6mXhsPy42N2PMX5BJtg8ihVekV68tf"
  expiration-time: 3600000  # 1 giờ (milliseconds)
  refresh-token-expiration-time: 604800000 # 7 ngày cho Refresh Token

#Cấu hình file upload
file: 
  upload-dir: ./upload

