# spring.application.name=be_e-commerce

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/be_e-commerce
    username: root
    password: Vuong123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: "0wyVcEIcIZR6ntVz/xbrFhH7l6izZZI8ob6mXhsPy42N2PMX5BJtg8ihVekV68tf"
  expiration-time: 3600000  # 1 giờ (milliseconds)
  refresh-token-expiration-time: 604800000 # 7 ngày cho Refresh Token

#Cấu hình file upload
file: 
  upload-dir: ./upload

